//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutPageImage
    {
        public int ImageId { get; set; }
        public string ImageName { get; set; }
        public byte[] imageUrl { get; set; }
        public int TypeId { get; set; }
        public string TypeName { get; set; }
    }
}
